source 'https://rubygems.org'

gem 'rails',        '4.2.2'
gem 'sass-rails',   '5.0.2'
gem 'uglifier',     '2.5.3'
gem 'bootstrap-sass'
gem 'coffee-rails', '4.1.0'
gem 'jquery-rails', '4.0.3'
gem 'bootstrap-will_paginate'
gem 'turbolinks',   '2.3.0'
gem 'sidekiq'
gem 'sidekiq_mailer'
gem 'sidetiq'
gem 'celluloid'
gem 'sinatra', require: false
gem 'slim'
gem 'resque'
gem 'redis-rails'
gem 'sidekiq-scheduler', '~> 2.0'
gem 'whenever', :require => false
gem 'twilio-ruby', '~> 3.12'
gem 'devise'
gem 'client_side_validations'
gem 'jbuilder',     '2.2.3'
gem 'redis-rack-cache'
gem 'ice_cube'
gem 'envyable'
gem 'sdoc',         '0.4.0', group: :doc
gem 'rspec-rails', :group => [:test, :development]

group :development, :test do
  gem 'sqlite3',     '1.3.9'
  gem 'byebug',      '3.4.0'
  gem 'web-console', '2.0.0.beta3'
  gem 'spring',      '1.1.3'
end

group :test do
  gem 'minitest-reporters', '1.0.5'
  gem 'mini_backtrace',     '0.1.3'
  gem 'guard-minitest',     '2.3.1'
  gem 'factory_girl_rails'
  gem 'capybara' #tests webapps by simulating how a real user would interact with app
  gem 'guard-rspec'
end

group :production do
  gem 'pg'            
  gem 'rails_12factor', '0.0.2'
end